<div class='container'>
  <div class='row'>
    <div class='col-xs-12'>
      <h2>Out Now</h2>
    </div>
    <div class='col-xs-12'>
      <div class='slickslider row'>
        <div class='col-xs-4 col-md-2'>
          <a href='https://www.amazon.co.uk/Horror-Story-Collection-CW-Lynch-ebook/dp/B006YG7C1O/'>
            <img src='https://www.cwlynch.com/wp-content/uploads/2016/12/HorrorStoryCollection1-566x800.jpg'>
          </a>
        </div>
        <div class='col-xs-4 col-md-2'>
          <a href='https://www.amazon.co.uk/dp/B06WV74W4B/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1486650301&sr=1-1&keywords=Shadows+And+Teeth%3A+Ten+Terrifying+Tales+Of+Horror+And+Suspense'>
            <img src='https://www.cwlynch.com/wp-content/uploads/2017/01/C28lPf6XAAE5Q4S-533x800.jpg'>
          </a>
        </div>
        <div class='col-xs-4 col-md-2'>
          <a href='https://www.amazon.co.uk/Dark-Graphic-Novel-Chirs-Lynch-ebook/dp/B00OOQ15VO'>
            <img src='https://www.cwlynch.com/wp-content/uploads/2016/12/TheDark_BristolCover.gif'>
          </a>
        </div>
        <div class='col-xs-12 hidden-md hidden-lg'>
          &nbsp;
        </div>
        <div class='col-xs-4 col-md-2'>
          <a href='https://www.amazon.co.uk/Circus-Death-Magpye-Book-1-ebook/dp/B00G3BKUSW/'>
            <img src='https://www.cwlynch.com/wp-content/uploads/2016/12/CircusOfDeath-564x800.jpg'>
          </a>
        </div>
        <div class='col-xs-4 col-md-2'>
          <a href='https://www.amazon.co.uk/Vault-of-Terror/dp/0973946571/'>
            <img src='https://www.cwlynch.com/wp-content/uploads/2017/02/517RX8DER9L.jpg'>
          </a>
        </div>
        <div class='col-xs-4 col-md-2'>
          <a href='https://www.amazon.co.uk/Budget-Android-Tablet-Buyers-Guide-ebook/dp/B00G97233U'>
            <img src='https://www.cwlynch.com/wp-content/uploads/2017/02/51brg4-k5CL.jpg'>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>